package ogrenci;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class NormalOgretim extends javax.swing.JFrame {

    /**
     * Creates new form NormalOgretim
     */
    public NormalOgretim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kytLabel = new javax.swing.JLabel();
        gecenButton = new javax.swing.JButton();
        cnsLabel = new javax.swing.JLabel();
        ogrScrollPane = new javax.swing.JScrollPane();
        ogrTable = new javax.swing.JTable();
        getirButton = new javax.swing.JButton();
        cinsiyetButton = new javax.swing.JButton();
        erkekRadioButton = new javax.swing.JRadioButton();
        kadınRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kytLabel.setText("Kayıtlar");

        gecenButton.setText("Dersi Geçenleri Göster");
        gecenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gecenButtonActionPerformed(evt);
            }
        });

        cnsLabel.setText("Cinsiyet");

        ogrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ogrScrollPane.setViewportView(ogrTable);

        getirButton.setText("Tüm Kayıtları Getir");
        getirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getirButtonActionPerformed(evt);
            }
        });

        cinsiyetButton.setText("Cinsiyete Göre Göster");
        cinsiyetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinsiyetButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(erkekRadioButton);
        erkekRadioButton.setText("Erkek");

        buttonGroup1.add(kadınRadioButton);
        kadınRadioButton.setText("Kadın");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kytLabel)
                    .addComponent(ogrScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getirButton)
                            .addComponent(gecenButton))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cnsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(erkekRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kadınRadioButton))
                            .addComponent(cinsiyetButton))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kytLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ogrScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnsLabel)
                    .addComponent(getirButton)
                    .addComponent(erkekRadioButton)
                    .addComponent(kadınRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gecenButton)
                    .addComponent(cinsiyetButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection getConnection() {
        Connection con = null;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String strdatabase = "jdbc:ucanaccess://NO.accdb";
            con = DriverManager.getConnection(strdatabase);
        } catch (Exception exp) {
            System.out.println(exp.getMessage());
        }
        return con;
    }


    private void gecenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gecenButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM OGRENCI");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM OGRENCI WHERE ORTALAMA > 60");
            Object[][] kayit = new Object[no][4];
            String ad, soyad, cinsiyet;
            int ort;
            no = 0;

            while (rs.next()) {
                ad = rs.getString("AD");
                soyad = rs.getString("SOYAD");
                cinsiyet = rs.getString("CINSIYET");
                ort = rs.getInt("ORTALAMA");

                kayit[no][0] = ad;
                kayit[no][1] = soyad;
                kayit[no][2] = cinsiyet;
                kayit[no][3] = ort;
                no++;
            }

            ogrTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"AD", "SOYAD", "CİNSİYET", "ORTALAMA"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_gecenButtonActionPerformed

    private void getirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getirButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM OGRENCI");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM OGRENCI");
            Object[][] kayit = new Object[no][4];
            String ad, soyad, cinsiyet;
            int ort;
            no = 0;

            while (rs.next()) {
                ad = rs.getString("AD");
                soyad = rs.getString("SOYAD");
                cinsiyet = rs.getString("CINSIYET");
                ort = rs.getInt("ORTALAMA");

                kayit[no][0] = ad;
                kayit[no][1] = soyad;
                kayit[no][2] = cinsiyet;
                kayit[no][3] = ort;
                no++;
            }

            ogrTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"AD", "SOYAD", "CİNSİYET", "ORTALAMA"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_getirButtonActionPerformed

    private void cinsiyetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinsiyetButtonActionPerformed
        // TODO add your handling code here:
        String cinsiyetText = "";

        if (erkekRadioButton.isSelected()) {
            cinsiyetText = erkekRadioButton.getText();
        } else if (kadınRadioButton.isSelected()) {
            cinsiyetText = kadınRadioButton.getText();
        } else {
            return;
        }
        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM OGRENCI");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM OGRENCI WHERE CINSIYET='" + cinsiyetText + "'");
            Object[][] kayit = new Object[no][4];
            String ad, soyad, cinsiyet;
            int ort;
            no = 0;

            while (rs.next()) {
                ad = rs.getString("AD");
                soyad = rs.getString("SOYAD");
                cinsiyet = rs.getString("CINSIYET");
                ort = rs.getInt("ORTALAMA");

                kayit[no][0] = ad;
                kayit[no][1] = soyad;
                kayit[no][2] = cinsiyet;
                kayit[no][3] = ort;
                no++;
            }

            ogrTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"AD", "SOYAD", "CİNSİYET", "ORTALAMA"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_cinsiyetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalOgretim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cinsiyetButton;
    private javax.swing.JLabel cnsLabel;
    private javax.swing.JRadioButton erkekRadioButton;
    private javax.swing.JButton gecenButton;
    private javax.swing.JButton getirButton;
    private javax.swing.JRadioButton kadınRadioButton;
    private javax.swing.JLabel kytLabel;
    private javax.swing.JScrollPane ogrScrollPane;
    private javax.swing.JTable ogrTable;
    // End of variables declaration//GEN-END:variables
}
