package dersSec;


import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author musta
 */
public class GPDLAB9_IO extends javax.swing.JFrame {

    /**
     * Creates new form GPDLAB9_IO
     */
    public GPDLAB9_IO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dersPanel = new javax.swing.JPanel();
        onayPanel = new javax.swing.JPanel();
        ekleButton = new javax.swing.JButton();
        onaylaButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ders Seçimi"));

        javax.swing.GroupLayout dersPanelLayout = new javax.swing.GroupLayout(dersPanel);
        dersPanel.setLayout(dersPanelLayout);
        dersPanelLayout.setHorizontalGroup(
            dersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dersPanelLayout.setVerticalGroup(
            dersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        onayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Danışman Onayı"));
        onayPanel.setPreferredSize(new java.awt.Dimension(411, 139));

        javax.swing.GroupLayout onayPanelLayout = new javax.swing.GroupLayout(onayPanel);
        onayPanel.setLayout(onayPanelLayout);
        onayPanelLayout.setHorizontalGroup(
            onayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        onayPanelLayout.setVerticalGroup(
            onayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        ekleButton.setText("Dersleri Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        onaylaButton.setText("Onayla");
        onaylaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Sıfırla");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(ekleButton)
                .addGap(18, 18, 18)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(onaylaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(onayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekleButton)
                    .addComponent(resetButton))
                .addGap(29, 29, 29)
                .addComponent(onayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onaylaButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed

        onayPanel.removeAll(); // Önce paneli temizle
        GridLayout layout = new GridLayout(4, 1);
        onayPanel.setLayout(layout);

        Component[] dersComponents = dersPanel.getComponents();

        for (int i = 0; i < dersComponents.length; i += 3) { // Her satırda 3 bileşen olduğu için 3 artırıldı (Döngü her aşamada 1 satırı işliyor) 
            JLabel dersLabel = (JLabel) dersComponents[i];
            JComboBox comboBox = (JComboBox) dersComponents[i + 2];

            String secim = (String) comboBox.getSelectedItem();
            if (secim == null) {
                continue;
            }

            JCheckBox checkBox = new JCheckBox();
            checkBox.setText(dersLabel.getText());
            checkBox.setName("" + i);
            // Renk belirleme

            switch (secim) {
                case "Alttan":
                    checkBox.setForeground(Color.RED);
                    break;
                case "Yeni":
                    checkBox.setForeground(Color.GREEN);
                    break;
                case "Üstten":
                    checkBox.setForeground(Color.ORANGE);
                    break;
            }

            onayPanel.add(checkBox);

        }

        onayPanel.revalidate();
        onayPanel.repaint();


    }//GEN-LAST:event_ekleButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {

            // Panelin temiz olduğundan emin olun
            dersPanel.removeAll();

            dersPanel.setLayout(new GridLayout(4, 3));

            // Dosyayı oku
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(new FileInputStream("src\\dersSec\\dersler.txt"), "UTF-8")
            );
            String line;
            int i = 0;
            while ((line = reader.readLine()) != null) {
                // Soru etiketi oluştur

                String[] parcalar = line.split(",");

                JLabel label = new JLabel(parcalar[0]);

                label.setName("Ders " + i);

                JLabel label2 = new JLabel(parcalar[1]);

                label.setName("Kredi " + i);

                // ComboBox oluştur ve seçenekleri ekle
                JComboBox comboBox = new JComboBox();
                comboBox.addItem("Alttan");
                comboBox.addItem("Yeni");
                comboBox.addItem("Üstten");

                comboBox.setName("Cevap " + i);

                // Panele ekle
                dersPanel.add(label);
                dersPanel.add(label2);
                dersPanel.add(comboBox);

            }
            reader.close();

            // Paneli yeniden çiz
            dersPanel.revalidate();
            dersPanel.repaint();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Dosya okunamadı: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:

        onayPanel.removeAll();
        onayPanel.revalidate();
        onayPanel.repaint();
        Component[] dersComponents = dersPanel.getComponents();
        for (int i = 0; i < dersComponents.length; i++) {
            Component comp = dersComponents[i];
            if (comp instanceof JComboBox) {
                JComboBox comboBox = (JComboBox) comp;
                comboBox.setSelectedIndex(-1); // Seçimi temizle
            } else if (comp instanceof JLabel) {
                JLabel label = (JLabel) comp;
                label.setForeground(Color.black);
            }
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void onaylaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaButtonActionPerformed
        // TODO add your handling code here:
        Component[] onayComponents = onayPanel.getComponents();

        Component[] dersComponents = dersPanel.getComponents();

        String text = "Dersler Onaylandı: ";
        for (int i = 0; i < onayComponents.length; i++) {
            Component comp = onayComponents[i];
            if (comp instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) comp;
                String name = checkBox.getName();

                if (name != null) {
                    try {
                        int index = Integer.parseInt(name);
                        JLabel dersLabel = (JLabel) dersComponents[index]; // Ders label

                        if (checkBox.isSelected()) {
                            dersLabel.setForeground(Color.GREEN); // işaretli => yeşil
                            text = text + checkBox.getText() + " ";
                        } else {
                            dersLabel.setForeground(Color.RED);   // işaretli değil => kırmızı
                        }
                    } catch (Exception e) {
                        System.out.println("Hata: " + e.getMessage());
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(this, text);

    }//GEN-LAST:event_onaylaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_IO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_IO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_IO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_IO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPDLAB9_IO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dersPanel;
    private javax.swing.JButton ekleButton;
    private javax.swing.JPanel onayPanel;
    private javax.swing.JButton onaylaButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
