/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aracpaketi;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aysegul
 */
public class NewJFrame extends javax.swing.JFrame {

    Vector<String> araclar;
    Vector<String> fiyatlar;
    Vector<String> eklenecekler;
    DefaultListModel<String> sepetModel;
    //ArrayList<sepeticerigiClass> sepeticerigi;

    /**
     * Creates new form anasayfa
     */
    public NewJFrame() {
        initComponents();
        araclar = new Vector<>();
        fiyatlar = new Vector<>();
        eklenecekler = new Vector<>();

        fiyattextfield.setEditable(false);
        toplamfiyattext.setEditable(false);

        sepetModel = new DefaultListModel<>();
        sepetlist.setModel(sepetModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        sepetekranidialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        sepetlist = new javax.swing.JList<>();
        toplamfiyattext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sepetonaylabuton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        araclarcombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fiyattextfield = new javax.swing.JTextField();
        ustPaketCheckBox = new javax.swing.JCheckBox();
        sepeteklebuton = new javax.swing.JButton();
        sepetgoruntulebuton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dosyaokubuton = new javax.swing.JMenuItem();

        sepetekranidialog.setTitle("Sepet");
        sepetekranidialog.setAlwaysOnTop(true);
        sepetekranidialog.setSize(new java.awt.Dimension(800, 400));

        jScrollPane1.setViewportView(sepetlist);

        jLabel3.setText("Toplam Tutar");

        sepetonaylabuton.setText("Sepeti Onayla");
        sepetonaylabuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetonaylabutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sepetekranidialogLayout = new javax.swing.GroupLayout(sepetekranidialog.getContentPane());
        sepetekranidialog.getContentPane().setLayout(sepetekranidialogLayout);
        sepetekranidialogLayout.setHorizontalGroup(
            sepetekranidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepetekranidialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(sepetekranidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepetonaylabuton)
                    .addComponent(toplamfiyattext, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63))
        );
        sepetekranidialogLayout.setVerticalGroup(
            sepetekranidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepetekranidialogLayout.createSequentialGroup()
                .addGroup(sepetekranidialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sepetekranidialogLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sepetekranidialogLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toplamfiyattext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sepetonaylabuton)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("231213000");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(200, 200));

        jLabel1.setText("Araç");

        araclarcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araclarcomboboxActionPerformed(evt);
            }
        });

        jLabel2.setText("Fiyat");

        ustPaketCheckBox.setText("Üst Paket (+ %20)");

        sepeteklebuton.setText("Sepete Ekle");
        sepeteklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepeteklebutonActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(araclarcombobox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fiyattextfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ustPaketCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(sepeteklebuton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(araclarcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ustPaketCheckBox))
                .addGap(25, 25, 25)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fiyattextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sepeteklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiyattextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(araclarcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ustPaketCheckBox)
                .addGap(18, 18, 18)
                .addComponent(sepeteklebuton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        sepetgoruntulebuton.setText("Sepeti Görüntüle");
        sepetgoruntulebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetgoruntulebutonActionPerformed(evt);
            }
        });

        jMenu1.setText("Dosya");

        dosyaokubuton.setText("Dosya Oku");
        dosyaokubuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaokubutonActionPerformed(evt);
            }
        });
        jMenu1.add(dosyaokubuton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(sepetgoruntulebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sepetgoruntulebuton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosyaokubutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaokubutonActionPerformed

        // FileChooser ile dosya okuma 
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                FileReader fr = new FileReader(jFileChooser1.getSelectedFile().getAbsolutePath());
                BufferedReader br = new BufferedReader(fr);
                String line = br.readLine();

                while (line != null) {
                    String[] parcala = line.split(",");

                    araclar.addElement(parcala[0]);
                    fiyatlar.addElement(parcala[1]);
                    line = br.readLine();
                }

                araclarcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(araclar));
                String secilenFiyat = fiyatlar.get(0);
                fiyattextfield.setText(secilenFiyat);

            } catch (IOException ee) {
                JOptionPane.showMessageDialog(null, "Hata", "Dosya bulunamadı", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ee) {
                JOptionPane.showMessageDialog(null, "Hata", "Dosya formatını kontrol edin", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_dosyaokubutonActionPerformed

    private void araclarcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araclarcomboboxActionPerformed
        int secilenIndex = araclarcombobox.getSelectedIndex();

        String secilenFiyat = fiyatlar.get(secilenIndex);
        fiyattextfield.setText(secilenFiyat);
    }//GEN-LAST:event_araclarcomboboxActionPerformed

    private void sepeteklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepeteklebutonActionPerformed
        String secilenarac = (String) araclarcombobox.getSelectedItem();
        if (secilenarac == null) {
            JOptionPane.showMessageDialog(this, "Lütfen önce bir araç seçin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int aracfiyat = Integer.parseInt(fiyattextfield.getText());
        int sonfiyat = aracfiyat;
        if (ustPaketCheckBox.isSelected()) {
            sonfiyat = (int) (aracfiyat * 1.2);
        }

        String mesaj = "Ürün sepete eklendi.\n"
                + "Araç: " + secilenarac + "\n"
                + "Fiyat: " + aracfiyat + " TL\n";

        // Sepeti ekle ve başarı mesajı göster
        JOptionPane.showMessageDialog(this, mesaj, "Başarılı", JOptionPane.INFORMATION_MESSAGE);

        String text = secilenarac + "," + aracfiyat + "," + sonfiyat;

        eklenecekler.add(text);

    }//GEN-LAST:event_sepeteklebutonActionPerformed

    private void sepetgoruntulebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetgoruntulebutonActionPerformed
        if (!eklenecekler.isEmpty()) {
            DefaultListModel<String> model = new DefaultListModel<>();
            int toplamFiyat = 0;  // Toplam fiyatı tutacak değişken

            for (int i = 0; i < eklenecekler.size(); i++) {
                String item = eklenecekler.get(i);

                model.addElement(item);
                int fiyat = Integer.valueOf(item.split(",")[2]);

                // Fiyatları topla (arac fiyatı + eklenti fiyatı)
                toplamFiyat += fiyat;
            }

            // Listeyi güncelle
            sepetlist.setModel(model);

            // Toplam fiyatı toplamfiyattext'e yaz
            toplamfiyattext.setText("" + toplamFiyat);

            // Dialogu ortada aç
            sepetekranidialog.setLocationRelativeTo(this);
            sepetekranidialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen önce sepete araç Ekleyin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_sepetgoruntulebutonActionPerformed

    private void sepetonaylabutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetonaylabutonActionPerformed
        // Sipariş kaydedilecek dosyayı seçmek için JFileChooser açılıyor
        if (jFileChooser1.showSaveDialog(sepetekranidialog) == JFileChooser.APPROVE_OPTION) {
            try {
                // Seçilen dosya yoluna yazmak için FileWriter ve BufferedWriter kullanılıyor
                FileWriter fw = new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(), false);
                BufferedWriter bw = new BufferedWriter(fw);

                // Sepet bilgilerini ve her aracın detaylarını almak için sepetteki her öğeyi döngüyle işliyoruz
                for (int i = 0; i < sepetlist.getModel().getSize(); i++) {
                    String item = sepetlist.getModel().getElementAt(i);

                    String[] parcala = item.split(",");

                    String text = "Araç//" + parcala[0] + "//Son Fiyat//" + parcala[2];
                    // Yazma işlemini tamamlayalım
                    bw.write(text + "\n");
                }

                // Dosyayı kapatıyoruz
                bw.close();

                sepetekranidialog.setVisible(false);
                // Kullanıcıya başarılı bir şekilde kaydedildiğini bildiriyoruz
                JOptionPane.showMessageDialog(this, "Sipariş kaydedildi: " + jFileChooser1.getSelectedFile().getAbsolutePath());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_sepetonaylabutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);  // Formu oluştur ve göster
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> araclarcombobox;
    private javax.swing.JMenuItem dosyaokubuton;
    private javax.swing.JTextField fiyattextfield;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sepeteklebuton;
    private javax.swing.JDialog sepetekranidialog;
    private javax.swing.JButton sepetgoruntulebuton;
    private javax.swing.JList<String> sepetlist;
    private javax.swing.JButton sepetonaylabuton;
    private javax.swing.JTextField toplamfiyattext;
    private javax.swing.JCheckBox ustPaketCheckBox;
    // End of variables declaration//GEN-END:variables
}
