import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nurul
 */
public class NewJFrame extends javax.swing.JFrame {
    JFileChooser fileChooser = new JFileChooser();
    /**
     * Creates new form IO
     */
    public NewJFrame() {
        initComponents();
        txtBolge.setEditable(false);
        btnFiltrele.setEnabled(false);
        txtSehirBolge.setEditable(false);
        txtSonuclar.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSehirBolge = new javax.swing.JTextArea();
        btnFiltrele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSonuclar = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtBolge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        dosya = new javax.swing.JMenu();
        bilgiOku = new javax.swing.JMenuItem();
        bolgeKaydet = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("231220000");

        txtSehirBolge.setEditable(false);
        txtSehirBolge.setColumns(20);
        txtSehirBolge.setRows(5);
        jScrollPane1.setViewportView(txtSehirBolge);

        btnFiltrele.setText("Filtrele");
        btnFiltrele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltreleActionPerformed(evt);
            }
        });

        jLabel1.setText("Şehir ve Bölge Bilgileri");

        txtSonuclar.setEditable(false);
        txtSonuclar.setColumns(20);
        txtSonuclar.setRows(5);
        jScrollPane2.setViewportView(txtSonuclar);

        jLabel2.setText("Bölge Giriniz");

        jLabel3.setText("Sonuçlar");

        dosya.setText("DOSYA");

        bilgiOku.setText("Şehir-Bölge bilgisi oku");
        bilgiOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiOkuActionPerformed(evt);
            }
        });
        dosya.add(bilgiOku);

        bolgeKaydet.setText("Bölge Kaydet");
        bolgeKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolgeKaydetActionPerformed(evt);
            }
        });
        dosya.add(bolgeKaydet);

        cikis.setText("Çıkış");
        dosya.add(cikis);

        jMenuBar1.add(dosya);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBolge, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrele)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnFiltrele)
                        .addGap(18, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBolge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgiOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiOkuActionPerformed
        // TODO add your handling code here:
        txtSehirBolge.setText("");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
        {
            try
            {
                BufferedReader br = new BufferedReader(new InputStreamReader(
                        new FileInputStream(fileChooser.getSelectedFile()), "UTF-8"));
                String line;
                while ((line = br.readLine()) != null)
                {
                    txtSehirBolge.append(line + "\n");
                }   
                br.close();
                txtBolge.setEditable(true);
                btnFiltrele.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Şehir ve bölge bilgileri başarıyla okundu!");
            }
            catch (IOException e)
            {
                JOptionPane.showMessageDialog(this, "Dosya okunamadı: " + e.getMessage());
            }    
        }
    }//GEN-LAST:event_bilgiOkuActionPerformed

    private void btnFiltreleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreleActionPerformed
        // TODO add your handling code here:
        txtSonuclar.setText("");
        String girilenBolge = txtBolge.getText();
        
        try
        {
            String[] satirlar = txtSehirBolge.getText().split("\n");
            
            for (int i = 0; i < satirlar.length; i++)
            {
                String[] parcalar = satirlar[i].split(",");
                if (parcalar.length == 2) 
                {
                    String bolge = parcalar[1];
                    if (bolge.equals(girilenBolge))                    
                        txtSonuclar.append(satirlar[i] + "\n");
                }
            }
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
        }    
    }//GEN-LAST:event_btnFiltreleActionPerformed
    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        System.exit(0);
    }
    private void bolgeKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolgeKaydetActionPerformed
        // TODO add your handling code here:
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) 
        {
            try
            {
                FileOutputStream fos = new FileOutputStream(jFileChooser1.getSelectedFile().getAbsolutePath(), false);
                OutputStreamWriter osr = new OutputStreamWriter(fos,Charset.forName("ISO-8859-9"));
                BufferedWriter bw = new BufferedWriter(osr);
                String[] satirlar = txtSonuclar.getText().split("\n");
                for(int i=0;i<satirlar.length;i++)
                    bw.write(satirlar[i] + "\t\n");
                bw.close(); //yazılan dosya kapatılmalıdır
                JOptionPane.showMessageDialog(null, "Dosyaya yazıldı!", "", JOptionPane.INFORMATION_MESSAGE);
            }
            catch (IOException hata)
            {
                JOptionPane.showMessageDialog(null, hata.getMessage());        
            }                    
        }
    }//GEN-LAST:event_bolgeKaydetActionPerformed
                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bilgiOku;
    private javax.swing.JMenuItem bolgeKaydet;
    private javax.swing.JButton btnFiltrele;
    private javax.swing.JMenuItem cikis;
    private javax.swing.JMenu dosya;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBolge;
    private javax.swing.JTextArea txtSehirBolge;
    private javax.swing.JTextArea txtSonuclar;
    // End of variables declaration//GEN-END:variables
}
