package anket;


import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author musta
 */
public class GPDLAB9_NO extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GPDLAB9_NO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anketPanel = new javax.swing.JPanel();
        gonderButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        bilgiPanel = new javax.swing.JPanel();
        adEkleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        anketPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Anket Formu"));
        anketPanel.setMinimumSize(new java.awt.Dimension(389, 232));
        anketPanel.setPreferredSize(new java.awt.Dimension(389, 232));

        javax.swing.GroupLayout anketPanelLayout = new javax.swing.GroupLayout(anketPanel);
        anketPanel.setLayout(anketPanelLayout);
        anketPanelLayout.setHorizontalGroup(
            anketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        anketPanelLayout.setVerticalGroup(
            anketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        gonderButton.setText("Formu Gönder");
        gonderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Anketi Sıfırla");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        bilgiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cevaplayan Bilgileri"));
        bilgiPanel.setMinimumSize(new java.awt.Dimension(389, 140));
        bilgiPanel.setPreferredSize(new java.awt.Dimension(389, 140));

        javax.swing.GroupLayout bilgiPanelLayout = new javax.swing.GroupLayout(bilgiPanel);
        bilgiPanel.setLayout(bilgiPanelLayout);
        bilgiPanelLayout.setHorizontalGroup(
            bilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        bilgiPanelLayout.setVerticalGroup(
            bilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        adEkleButton.setText("Ad Soyad Ekle");
        adEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adEkleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bilgiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(adEkleButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gonderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bilgiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adEkleButton)
                .addGap(30, 30, 30)
                .addComponent(anketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gonderButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {

            // Panelin temiz olduğundan emin olun
            anketPanel.removeAll();

            GridLayout layout = new GridLayout(4, 2);
            layout.setHgap(3);
            anketPanel.setLayout(layout);

            // Dosyayı oku
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(new FileInputStream("src\\anket\\anket.txt"), "UTF-8")
            );
            String line;
            int i = 0;
            line = reader.readLine();
            while (line != null) {
                // Soru etiketi oluştur
                JLabel label = new JLabel(line);
                label.setName("Soru " + i);

                // ComboBox oluştur ve seçenekleri ekle
                JComboBox comboBox = new JComboBox();
                comboBox.addItem("1");
                comboBox.addItem("2");
                comboBox.addItem("3");

                comboBox.setName("Cevap " + i);

                // Panele ekle
                anketPanel.add(label);
                anketPanel.add(comboBox);
                line = reader.readLine();

            }
            reader.close();

            // Paneli yeniden çiz
            anketPanel.revalidate();
            anketPanel.repaint();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Dosya okunamadı: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void gonderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderButtonActionPerformed
        // TODO add your handling code here:

        String text = "";
        Component[] bilgiComponents = bilgiPanel.getComponents();
        Component[] anketComponents = anketPanel.getComponents();
        if (bilgiComponents.length == 1) {
            JOptionPane.showMessageDialog(this, "Ad Soyad Paneline bilgiler girilmedi!", "Hata", JOptionPane.ERROR_MESSAGE);
        } else if (anketComponents.length == 1) {
            JOptionPane.showMessageDialog(this, "Anket yüklenmedi!", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < bilgiComponents.length; i++) {
                Component comp = bilgiComponents[i];
                if (comp.getName() != null && comp.getName().equals("ad")) {
                    JTextField adField = (JTextField) comp;
                    text = "Ad: " + adField.getText() + " ";
                } else if (comp.getName() != null && comp.getName().equals("soyad")) {
                    JTextField soyadField = (JTextField) comp;
                    text = text + "Soyad: " + soyadField.getText() + "\n";
                }
            }

            text = text + "Cevaplar:";

            for (int i = 0; i < anketComponents.length; i++) {
                if (anketComponents[i] instanceof JLabel) {

                    JLabel label = (JLabel) anketComponents[i];

                    JComboBox comboBox = (JComboBox) anketComponents[i + 1];
                    String cevap = (String) comboBox.getSelectedItem();

                    text = text + " " + cevap;

                    if (cevap != null) {
                        if (cevap.equals("1")) {
                            label.setForeground(Color.RED);

                        } else if (cevap.equals("2")) {
                            label.setForeground(Color.BLUE);

                        } else if (cevap.equals("3")) {
                            label.setForeground(Color.GREEN);

                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(this, text);
        }

    }//GEN-LAST:event_gonderButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:     

        bilgiPanel.removeAll();

        Component[] anketComponents = anketPanel.getComponents();
        for (int i = 0; i < anketComponents.length; i++) {
            Component comp = anketComponents[i];
            if (comp instanceof JLabel) {
                JLabel label = (JLabel) comp;
                label.setForeground(Color.BLACK); // Rengi sıfırla
            } else if (comp instanceof JComboBox) {
                JComboBox comboBox = (JComboBox) comp;
                comboBox.setSelectedIndex(-1); // Seçimi temizle
            }
        }


    }//GEN-LAST:event_resetButtonActionPerformed

    private void adEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adEkleButtonActionPerformed
        // TODO add your handling code here:

        bilgiPanel.removeAll();

        JLabel adLabel = new JLabel("Adınız: ");
        JLabel soyadLabel = new JLabel("Soyadınız: ");

        JTextField adTextField = new JTextField();
        JTextField soyadTextField = new JTextField();

        adTextField.setName("ad");
        soyadTextField.setName("soyad");

        bilgiPanel.setLayout(new GridLayout(2, 2));
        bilgiPanel.add(adLabel);
        bilgiPanel.add(adTextField);
        bilgiPanel.add(soyadLabel);
        bilgiPanel.add(soyadTextField);

        // Paneli yeniden çiz
        bilgiPanel.revalidate();
        bilgiPanel.repaint();

    }//GEN-LAST:event_adEkleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPDLAB9_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPDLAB9_NO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adEkleButton;
    private javax.swing.JPanel anketPanel;
    private javax.swing.JPanel bilgiPanel;
    private javax.swing.JButton gonderButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
