/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siparispaketi;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aysegul
 */
public class NewJFrame extends javax.swing.JFrame {

    DefaultListModel<String> yemekler;
    Vector<String> fiyatlar;

    /**
     * Creates new form Frame
     */
    public NewJFrame() {
        initComponents();
        yemekler = new DefaultListModel();
        fiyatlar = new Vector<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siparislerDialog = new javax.swing.JDialog();
        siparisOnaylaButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        toplamTutarTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        siparislerTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jOptionPane2 = new javax.swing.JOptionPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yemekList = new javax.swing.JList<>();
        fiyatTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adetTextField = new javax.swing.JTextField();
        yemekEkleButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        siparisGosterButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        siparislerDialog.setMinimumSize(new java.awt.Dimension(372, 410));

        siparisOnaylaButton.setText("Siparişi Onayla");
        siparisOnaylaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisOnaylaButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Toplam Tutar: ");

        toplamTutarTextField.setEditable(false);

        siparislerTextArea.setEditable(false);
        siparislerTextArea.setColumns(20);
        siparislerTextArea.setRows(5);
        jScrollPane2.setViewportView(siparislerTextArea);

        jLabel5.setText("Sipariş Listesi");

        javax.swing.GroupLayout siparislerDialogLayout = new javax.swing.GroupLayout(siparislerDialog.getContentPane());
        siparislerDialog.getContentPane().setLayout(siparislerDialogLayout);
        siparislerDialogLayout.setHorizontalGroup(
            siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparislerDialogLayout.createSequentialGroup()
                .addGroup(siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siparislerDialogLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(siparislerDialogLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(siparisOnaylaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(siparislerDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(toplamTutarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(siparislerDialogLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        siparislerDialogLayout.setVerticalGroup(
            siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparislerDialogLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(siparislerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(toplamTutarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(siparisOnaylaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("231220000");

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Yemek Listesi");

        yemekList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                yemekListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(yemekList);

        fiyatTextField.setEditable(false);

        jLabel2.setText("Adet");

        adetTextField.setText("1");

        yemekEkleButton.setText("Siparişe Ekle");
        yemekEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yemekEkleButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Fiyat");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fiyatTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(adetTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(yemekEkleButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(fiyatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(yemekEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(fiyatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(yemekEkleButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        siparisGosterButton.setText("SipariŞi Göster");
        siparisGosterButton.setActionCommand("Siparişi Göster");
        siparisGosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisGosterButtonActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Dosya");

        jMenuItem1.setText("Dosyayi Oku");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");
        jMenuBar1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(siparisGosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siparisGosterButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siparisGosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisGosterButtonActionPerformed
        // TODO add your handling code here:

        String text = siparislerTextArea.getText();
        String[] lines = text.split("\n");
        int toplamTutar = 0;
        for (int i = 0; i < lines.length; i++) {

            String line = lines[i];
            String[] parcala = line.split(",");
            int fiyat = Integer.valueOf(parcala[1]);
            int adet = Integer.valueOf(parcala[2]);

            int tutar = fiyat * adet;
            toplamTutar += tutar;
        }

        toplamTutarTextField.setText(String.valueOf(toplamTutar));
        siparislerDialog.setVisible(true);
    }//GEN-LAST:event_siparisGosterButtonActionPerformed

    private void siparisOnaylaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisOnaylaButtonActionPerformed
        // TODO add your handling code here:

        if (jFileChooser1.showSaveDialog(siparislerDialog) == JFileChooser.APPROVE_OPTION) {

            try {
                FileWriter fw = new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(), false);
                BufferedWriter bw = new BufferedWriter(fw);

                String text = siparislerTextArea.getText();
                String[] lines = text.split("\n");

                for (int i = 0; i < lines.length; i++) {

                    //yemek//<yemek>//adet//<adet>//fiyat//<fiyat>
                    String line = lines[i];
                    String[] parcala = line.split(",");

                    bw.write("yemek//" + parcala[0] + "//adet//" + parcala[2] + "//fiyat//" + parcala[1] + "\n");

                }

                bw.close();

                siparislerDialog.setVisible(false);

                JOptionPane.showMessageDialog(this, "Sipariş kaydedildi: " + jFileChooser1.getSelectedFile().getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_siparisOnaylaButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                FileReader fr = new FileReader(jFileChooser1.getSelectedFile().getAbsolutePath());
                BufferedReader br = new BufferedReader(fr);
                String line = br.readLine();

                for (int i = 0; line != null; i++) {
                    String[] parcala = line.split(",");
                    yemekler.addElement(parcala[0]);
                    fiyatlar.addElement(parcala[1]);
                    line = br.readLine();
                }
                br.close();

                yemekList.setModel(yemekler);

            } catch (IOException ee) {
                JOptionPane.showMessageDialog(null, "Hata", "Dosya bulunamadı", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ee) {
                JOptionPane.showMessageDialog(null, "Hata", "Dosya formatını kontrol edin", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void yemekListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_yemekListValueChanged
        // TODO add your handling code here:
        int index = yemekList.getSelectedIndex();
        String fiyat = fiyatlar.get(index);

        fiyatTextField.setText(fiyat);

    }//GEN-LAST:event_yemekListValueChanged

    private void yemekEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yemekEkleButtonActionPerformed
        // TODO add your handling code here:

        String eklenecekText = "";

        String yemek = yemekList.getSelectedValue();
        String fiyat = fiyatTextField.getText();
        String adet = adetTextField.getText();

        eklenecekText = yemek + "," + fiyat + "," + adet + "\n";

        siparislerTextArea.append(eklenecekText);

        JOptionPane.showMessageDialog(this, adet + " adet " + yemek + " siparişe eklendi. ");

    }//GEN-LAST:event_yemekEkleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adetTextField;
    private javax.swing.JTextField fiyatTextField;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton siparisGosterButton;
    private javax.swing.JButton siparisOnaylaButton;
    private javax.swing.JDialog siparislerDialog;
    private javax.swing.JTextArea siparislerTextArea;
    private javax.swing.JTextField toplamTutarTextField;
    private javax.swing.JButton yemekEkleButton;
    private javax.swing.JList<String> yemekList;
    // End of variables declaration//GEN-END:variables
}
