/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.gorsellab5;

import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author musta
 */
public class NO extends javax.swing.JFrame {

    /**
     * Creates new form NO
     */
    public NO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        dogruRenkDegistir = new javax.swing.JMenuItem();
        yanlisRenkDegistir = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dogruRadioButton = new javax.swing.JRadioButton();
        yanlisRadioButton = new javax.swing.JRadioButton();
        testTamamla = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        soruPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cevapTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cevapTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cevapTextField3 = new javax.swing.JTextField();
        renkPanel = new javax.swing.JPanel();
        renkTextField2 = new javax.swing.JTextField();
        renkTextField1 = new javax.swing.JTextField();
        cevaplaButton = new javax.swing.JButton();
        sonucGosterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        dogruRenkDegistir.setText("Doğru Cevap Rengi Değiştir");
        dogruRenkDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogruRenkDegistirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(dogruRenkDegistir);

        yanlisRenkDegistir.setText("Yanlış Cevap Rengi Değiştir");
        yanlisRenkDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yanlisRenkDegistirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(yanlisRenkDegistir);

        jDialog1.setTitle("Sorular");
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 300, 250));
        jDialog1.setMinimumSize(new java.awt.Dimension(450, 300));

        jLabel5.setText("Soru 1: Türkiye'nin başkenti neresidir?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "İstanbul", "Konya" }));

        jLabel6.setText("Soru 2: Türkiye Cumhuriyeti'nin kuruluş yılı nedir?");

        jLabel7.setText("Soru 3: Suyun donma noktası 0'dır. ");

        buttonGroup1.add(dogruRadioButton);
        dogruRadioButton.setText("Doğru");

        buttonGroup1.add(yanlisRadioButton);
        yanlisRadioButton.setText("Yanlış");

        testTamamla.setText("Testi Tamamla");
        testTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTamamlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(44, 44, 44)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yanlisRadioButton)
                            .addComponent(dogruRadioButton)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(testTamamla, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dogruRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yanlisRadioButton)))
                .addGap(7, 7, 7)
                .addComponent(testTamamla)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soruPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Test cevapları"));

        jLabel1.setText("Cevap 1");

        cevapTextField1.setEditable(false);

        jLabel2.setText("Cevap 2");

        cevapTextField2.setEditable(false);

        jLabel3.setText("Cevap 3");

        cevapTextField3.setEditable(false);

        javax.swing.GroupLayout soruPanelLayout = new javax.swing.GroupLayout(soruPanel);
        soruPanel.setLayout(soruPanelLayout);
        soruPanelLayout.setHorizontalGroup(
            soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soruPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soruPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cevapTextField3))
                    .addGroup(soruPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cevapTextField2)))
                .addContainerGap())
            .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(soruPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(cevapTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        soruPanelLayout.setVerticalGroup(
            soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soruPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cevapTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cevapTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
            .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(soruPanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(soruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cevapTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        renkPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Renk Seçimi"));
        renkPanel.setComponentPopupMenu(jPopupMenu1);

        renkTextField2.setEditable(false);
        renkTextField2.setBackground(new java.awt.Color(255, 0, 0));
        renkTextField2.setText("Yanlış Cevap Rengi");

        renkTextField1.setEditable(false);
        renkTextField1.setBackground(new java.awt.Color(102, 255, 0));
        renkTextField1.setText("Doğru Cevap Rengi");

        javax.swing.GroupLayout renkPanelLayout = new javax.swing.GroupLayout(renkPanel);
        renkPanel.setLayout(renkPanelLayout);
        renkPanelLayout.setHorizontalGroup(
            renkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(renkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(renkTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renkTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        renkPanelLayout.setVerticalGroup(
            renkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(renkTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(renkTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        cevaplaButton.setText("Test başlat");
        cevaplaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevaplaButtonActionPerformed(evt);
            }
        });

        sonucGosterButton.setText("Sonuç Göster");
        sonucGosterButton.setEnabled(false);
        sonucGosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucGosterButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("TEST UYGULAMASINA HOŞGELDİNİZ!..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(soruPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cevaplaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sonucGosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(renkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soruPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cevaplaButton)
                    .addComponent(sonucGosterButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dogruRenkDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogruRenkDegistirActionPerformed
        // TODO add your handling code here:
        renkTextField1.setBackground(jColorChooser1.showDialog(null, "Doğru Cevap Rengi Seçiniz", renkTextField2.getBackground()));
    }//GEN-LAST:event_dogruRenkDegistirActionPerformed

    private void yanlisRenkDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yanlisRenkDegistirActionPerformed
        // TODO add your handling code here:
        renkTextField2.setBackground(jColorChooser1.showDialog(null, "Yanlış Cevap Rengi Seçiniz", renkTextField1.getBackground()));
    }//GEN-LAST:event_yanlisRenkDegistirActionPerformed

    private void testTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTamamlaActionPerformed
        // TODO add your handling code here:
        String cevap1 = String.valueOf(jComboBox1.getSelectedItem());
        String cevap2 = jTextField6.getText();
        String cevap3 = "";
        if (dogruRadioButton.isSelected())
        {
            cevap3 = "Doğru";
        }
        if (yanlisRadioButton.isSelected())
        {
            cevap3 = "Yanlış";
        }

        cevapTextField1.setText(cevap1);
        cevapTextField2.setText(cevap2);
        cevapTextField3.setText(cevap3);

        jDialog1.setVisible(false);
        sonucGosterButton.setEnabled(true);
    }//GEN-LAST:event_testTamamlaActionPerformed

    private void cevaplaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevaplaButtonActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_cevaplaButtonActionPerformed

    private void sonucGosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucGosterButtonActionPerformed
        // TODO add your handling code here:
        int sonuc = 0;
        
        //Ankara için kontrol
        if (cevapTextField1.getText().equals("Ankara")) 
        {
            cevapTextField1.setBackground(renkTextField1.getBackground());
            sonuc++;
        } 
        else 
        {
            cevapTextField1.setBackground(renkTextField2.getBackground());
        }
        
        //1923 için kontrol
        if (cevapTextField2.getText().equals("1923")) 
        {
            cevapTextField2.setBackground(renkTextField1.getBackground());
            sonuc++;
        } 
        else 
        {
            cevapTextField2.setBackground(renkTextField2.getBackground());
        }
        
        //su donma için kontrol
        if (cevapTextField3.getText().equals("Doğru")) 
        {
            cevapTextField3.setBackground(renkTextField1.getBackground());
            sonuc++;
        } 
        else 
        {
            cevapTextField3.setBackground(renkTextField2.getBackground());
        }

        JOptionPane.showMessageDialog(this, "Sonucunuz: " + sonuc + "/3");
    }//GEN-LAST:event_sonucGosterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cevapTextField1;
    private javax.swing.JTextField cevapTextField2;
    private javax.swing.JTextField cevapTextField3;
    private javax.swing.JButton cevaplaButton;
    private javax.swing.JRadioButton dogruRadioButton;
    private javax.swing.JMenuItem dogruRenkDegistir;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel renkPanel;
    private javax.swing.JTextField renkTextField1;
    private javax.swing.JTextField renkTextField2;
    private javax.swing.JButton sonucGosterButton;
    private javax.swing.JPanel soruPanel;
    private javax.swing.JButton testTamamla;
    private javax.swing.JRadioButton yanlisRadioButton;
    private javax.swing.JMenuItem yanlisRenkDegistir;
    // End of variables declaration//GEN-END:variables
}
