package market;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class IkinciOgretim extends javax.swing.JFrame {

    /**
     * Creates new form IkinciOgretim
     */
    public IkinciOgretim() {
        initComponents();
    }

    public Connection getConnection() {
        Connection con = null;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String strdatabase = "jdbc:ucanaccess://IO.accdb";
            con = DriverManager.getConnection(strdatabase);
        } catch (Exception exp) {
            System.out.println(exp.getMessage());
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        urunLabel = new javax.swing.JLabel();
        marketScrollPane = new javax.swing.JScrollPane();
        marketTable = new javax.swing.JTable();
        getirButton = new javax.swing.JButton();
        azlarButton = new javax.swing.JButton();
        manavRadioButton = new javax.swing.JRadioButton();
        sarkuteriRadioButton = new javax.swing.JRadioButton();
        bakliyatRadioButton = new javax.swing.JRadioButton();
        reyonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urunLabel.setText("Ürünler");

        marketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        marketScrollPane.setViewportView(marketTable);

        getirButton.setText("Tüm Kayıtları Getir");
        getirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getirButtonActionPerformed(evt);
            }
        });

        azlarButton.setText("5'ten Az Olanları Getir");
        azlarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azlarButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(manavRadioButton);
        manavRadioButton.setText("Manav");
        manavRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manavRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sarkuteriRadioButton);
        sarkuteriRadioButton.setText("Bakliyat");

        buttonGroup1.add(bakliyatRadioButton);
        bakliyatRadioButton.setText("Şarküteri");

        reyonButton.setText("Reyondaki Ürünleri Getir");
        reyonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reyonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(marketScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(urunLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(azlarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(manavRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bakliyatRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sarkuteriRadioButton))
                                .addComponent(reyonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(urunLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marketScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getirButton)
                    .addComponent(manavRadioButton)
                    .addComponent(bakliyatRadioButton)
                    .addComponent(sarkuteriRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azlarButton)
                    .addComponent(reyonButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getirButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM MARKET");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM MARKET");
            Object[][] kayit = new Object[no][3];
            String urun, reyon;
            int adet;
            no = 0;

            while (rs.next()) {
                urun = rs.getString("URUN");
                reyon = rs.getString("REYON");
                adet = rs.getInt("ADET");

                kayit[no][0] = urun;
                kayit[no][1] = reyon;
                kayit[no][2] = adet;
                no++;
            }

            marketTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"Ürün", "Reyon", "Adet"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }

    }//GEN-LAST:event_getirButtonActionPerformed

    private void azlarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azlarButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM MARKET");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM MARKET WHERE ADET < 5");
            Object[][] kayit = new Object[no][3];
            String urun, reyon;
            int adet;
            no = 0;

            while (rs.next()) {
                urun = rs.getString("URUN");
                reyon = rs.getString("REYON");
                adet = rs.getInt("ADET");

                kayit[no][0] = urun;
                kayit[no][1] = reyon;
                kayit[no][2] = adet;
                no++;
            }

            marketTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"Ürün", "Reyon", "Adet"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_azlarButtonActionPerformed

    private void manavRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manavRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manavRadioButtonActionPerformed

    private void reyonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reyonButtonActionPerformed
        // TODO add your handling code here:
        String reyonText = "";

        if (manavRadioButton.isSelected()) {
            reyonText = manavRadioButton.getText();
        } else if (sarkuteriRadioButton.isSelected()) {
            reyonText = sarkuteriRadioButton.getText();
        } else if (bakliyatRadioButton.isSelected()) {
            reyonText = bakliyatRadioButton.getText();
        } else {
            return;
        }

        try {
            Connection con2 = getConnection();
            Statement stmt = con2.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM MARKET");
            rs.next();
            int no = rs.getInt("rowcount");
            rs.close();

            rs = stmt.executeQuery("SELECT * FROM MARKET WHERE REYON = '" + reyonText + "'");
            Object[][] kayit = new Object[no][3];
            String urun, reyon;
            int adet;
            no = 0;

            while (rs.next()) {
                urun = rs.getString("URUN");
                reyon = rs.getString("REYON");
                adet = rs.getInt("ADET");

                kayit[no][0] = urun;
                kayit[no][1] = reyon;
                kayit[no][2] = adet;
                no++;
            }

            marketTable.setModel(new javax.swing.table.DefaultTableModel(kayit,
                    new String[]{"Ürün", "Reyon", "Adet"}));
            con2.close();
        } catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_reyonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IkinciOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IkinciOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IkinciOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IkinciOgretim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IkinciOgretim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azlarButton;
    private javax.swing.JRadioButton bakliyatRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton getirButton;
    private javax.swing.JRadioButton manavRadioButton;
    private javax.swing.JScrollPane marketScrollPane;
    private javax.swing.JTable marketTable;
    private javax.swing.JButton reyonButton;
    private javax.swing.JRadioButton sarkuteriRadioButton;
    private javax.swing.JLabel urunLabel;
    // End of variables declaration//GEN-END:variables
}
