
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author senaoztekin
 */
public class LAB4NO extends javax.swing.JFrame {

    /**
     * Creates new form LAB4NO
     */
    
    public String TeknolojiMarketiAdi;
            
    public LAB4NO() {
        initComponents();                
    }
    
    public void changeName (String name)
    {        
        jLabel1.setText(name);       
    }
    
    DefaultListModel dlm = new DefaultListModel();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        sepetEkle = new javax.swing.JButton();
        sepetCikar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sepetSifirla = new javax.swing.JMenuItem();
        adDegistir = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SOYİSİM");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Teknoloji Ürünleri");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bilgisayar");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Asus");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Lenovo");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Macbook");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Telefon");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Samsung");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Iphone");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Huawei");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Beyaz Eşya");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Arçelik");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Bosch");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Siemens");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setViewportView(jList1);

        sepetEkle.setText("Sepete Ekle");
        sepetEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetEkleActionPerformed(evt);
            }
        });

        sepetCikar.setText("Sepetten Çıkar");
        sepetCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetCikarActionPerformed(evt);
            }
        });

        jLabel2.setText("SEPET");

        jMenu1.setText("Dosya");

        sepetSifirla.setText("Sepeti Sıfırla");
        sepetSifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetSifirlaActionPerformed(evt);
            }
        });
        jMenu1.add(sepetSifirla);

        adDegistir.setText("Ad Değiştir");
        adDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adDegistirActionPerformed(evt);
            }
        });
        jMenu1.add(adDegistir);

        cikis.setText("Çıkış Yap");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jMenu1.add(cikis);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(sepetCikar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sepetEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(sepetEkle)
                        .addGap(18, 18, 18)
                        .addComponent(sepetCikar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sepetSifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetSifirlaActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Evet",
                            "Hayır",
                            "İptal Et"};
        int secim = JOptionPane.showOptionDialog(null,
                                                 "Sepeti Sıfırlamak İstiyor Musunuz?",
                                                 "Sepeti Sıfırla",
                                                 JOptionPane.YES_NO_CANCEL_OPTION,
                                                 JOptionPane.QUESTION_MESSAGE,
                                                 null,
                                                 options,
                                                 options[0]);

        if(secim==0) 
        {
            dlm = (DefaultListModel)jList1.getModel();
            dlm.removeAllElements();
        }
        else
           JOptionPane.showMessageDialog(null, "Liste silme iptal edildi", "MESAJ_PNCR", JOptionPane.INFORMATION_MESSAGE);    
    }//GEN-LAST:event_sepetSifirlaActionPerformed

    private void adDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adDegistirActionPerformed
        // TODO add your handling code here:
        NewJFrameNO yeniPencere = new NewJFrameNO();
        yeniPencere.parent = this;   
        yeniPencere.TeknolojiMarketIsmi(jLabel1.getText());
        yeniPencere.setTitle("Ad Değiştir");
        yeniPencere.setVisible(true);   
    }//GEN-LAST:event_adDegistirActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    private void sepetEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetEkleActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode market_selected_node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if (market_selected_node.isLeaf())
        {
            dlm.addElement(market_selected_node); 
            jList1.setModel(dlm);
        }
        else
            JOptionPane.showMessageDialog(null, "Tek Ürün seçilmedi", "MESAJ_PNCR", JOptionPane.ERROR_MESSAGE);   
    }//GEN-LAST:event_sepetEkleActionPerformed

    private void sepetCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetCikarActionPerformed
        // TODO add your handling code here:
        dlm = (DefaultListModel)jList1.getModel();
        int[] indisler = jList1.getSelectedIndices();
        for(int i=0;i<indisler.length;i++)
            dlm.removeElementAt(indisler[i]);     
    }//GEN-LAST:event_sepetCikarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB4NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB4NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB4NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB4NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB4NO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adDegistir;
    private javax.swing.JMenuItem cikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton sepetCikar;
    private javax.swing.JButton sepetEkle;
    private javax.swing.JMenuItem sepetSifirla;
    // End of variables declaration//GEN-END:variables
}
